/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function getLights() {
    return invoke()<HueV2Response<HueV2Light>>("get_lights")
}

export function getLight(id: string) {
    return invoke()<HueV2Response<HueV2Light>>("get_light", { id })
}

export function getScenes() {
    return invoke()<HueV2Response<HueV2Scene>>("get_scenes")
}

export function getScene(id: string) {
    return invoke()<HueV2Response<HueV2Scene>>("get_scene", { id })
}

export function getRooms() {
    return invoke()<HueV2Response<HueV2Room>>("get_rooms")
}

export function getRoom(id: string) {
    return invoke()<HueV2Response<HueV2Room>>("get_room", { id })
}

export function getZones() {
    return invoke()<HueV2Response<HueV2Zone>>("get_zones")
}

export function getZone(id: string) {
    return invoke()<HueV2Response<HueV2Zone>>("get_zone", { id })
}

export function getBridgeHomes() {
    return invoke()<HueV2Response<HueV2BridgeHome>>("get_bridge_homes")
}

export function getBridgeHome(id: string) {
    return invoke()<HueV2Response<HueV2BridgeHome>>("get_bridge_home", { id })
}

export function getGroupedLights() {
    return invoke()<HueV2Response<HueV2GroupedLight>>("get_grouped_lights")
}

export function getGroupedLight(id: string) {
    return invoke()<HueV2Response<HueV2GroupedLight>>("get_grouped_light", { id })
}

export function getDevices() {
    return invoke()<HueV2Response<HueV2Device>>("get_devices")
}

export function getDevice(id: string) {
    return invoke()<HueV2Response<HueV2Device>>("get_device", { id })
}

export function getBridges() {
    return invoke()<HueV2Response<HueV2Bridge>>("get_bridges")
}

export function getBridge(id: string) {
    return invoke()<HueV2Response<HueV2Bridge>>("get_bridge", { id })
}

export function getDevicePowers() {
    return invoke()<HueV2Response<HueV2DevicePower>>("get_device_powers")
}

export function getDevicePower(id: string) {
    return invoke()<HueV2Response<HueV2DevicePower>>("get_device_power", { id })
}

export function getZigbeeConnectivities() {
    return invoke()<HueV2Response<HueV2ZigbeeConnectivity>>("get_zigbee_connectivities")
}

export function getZigbeeConnectivity(id: string) {
    return invoke()<HueV2Response<HueV2ZigbeeConnectivity>>("get_zigbee_connectivity", { id })
}

export function getZgpConnectivities() {
    return invoke()<HueV2Response<HueV2ZgpConnectivity>>("get_zgp_connectivities")
}

export function getZgpConnectivity(id: string) {
    return invoke()<HueV2Response<HueV2ZgpConnectivity>>("get_zgp_connectivity", { id })
}

export function getZigbeeDeviceDiscoveries(id: string) {
    return invoke()<HueV2Response<HueV2ZigbeeDeviceDiscovery>>("get_zigbee_device_discoveries", { id })
}

export function getZigbeeDeviceDiscovery() {
    return invoke()<HueV2Response<HueV2ZigbeeDeviceDiscovery>>("get_zigbee_device_discovery")
}

export function getTemperatures() {
    return invoke()<HueV2Response<HueV2Temperature>>("get_temperatures")
}

export function getTemperature(id: string) {
    return invoke()<HueV2Response<HueV2Temperature>>("get_temperature", { id })
}

export function getLightLevels() {
    return invoke()<HueV2Response<HueV2LightLevel>>("get_light_levels")
}

export function getLightLevel(id: string) {
    return invoke()<HueV2Response<HueV2LightLevel>>("get_light_level", { id })
}

export function getButtons() {
    return invoke()<HueV2Response<HueV2Button>>("get_buttons")
}

export function getButton(id: string) {
    return invoke()<HueV2Response<HueV2Button>>("get_button", { id })
}

export function getRelativeRotaries() {
    return invoke()<HueV2Response<HueV2RelativeRotary>>("get_relative_rotaries")
}

export function getRelativeRotary(id: string) {
    return invoke()<HueV2Response<HueV2RelativeRotary>>("get_relative_rotary", { id })
}

export function getBehaviourScripts() {
    return invoke()<HueV2Response<HueV2BehaviorScript>>("get_behaviour_scripts")
}

export function getBehaviourScript(id: string) {
    return invoke()<HueV2Response<HueV2BehaviorScript>>("get_behaviour_script", { id })
}

export function getBehaviourInstances() {
    return invoke()<HueV2Response<HueV2BehaviorInstance>>("get_behaviour_instances")
}

export function getBehaviourInstance(id: string) {
    return invoke()<HueV2Response<HueV2BehaviorInstance>>("get_behaviour_instance", { id })
}

export function getGeofenceClients() {
    return invoke()<HueV2Response<HueV2GeofenceClient>>("get_geofence_clients")
}

export function getGeofenceClient(id: string) {
    return invoke()<HueV2Response<HueV2GeofenceClient>>("get_geofence_client", { id })
}

export function getGeolocations() {
    return invoke()<HueV2Response<HueV2Geolocation>>("get_geolocations")
}

export function getGeolocation(id: string) {
    return invoke()<HueV2Response<HueV2Geolocation>>("get_geolocation", { id })
}

export function getEntertainmentConfigurations() {
    return invoke()<HueV2Response<HueV2EntertainmentConfiguration>>("get_entertainment_configurations")
}

export function getEntertainmentConfiguration(id: string) {
    return invoke()<HueV2Response<HueV2EntertainmentConfiguration>>("get_entertainment_configuration", { id })
}

export function getEntertainments() {
    return invoke()<HueV2Response<HueV2Entertainment>>("get_entertainments")
}

export function getEntertainment(id: string) {
    return invoke()<HueV2Response<HueV2Entertainment>>("get_entertainment", { id })
}

export function getHomekits() {
    return invoke()<HueV2Response<HueV2Homekit>>("get_homekits")
}

export function getHomekit(id: string) {
    return invoke()<HueV2Response<HueV2Homekit>>("get_homekit", { id })
}

export function getMatters() {
    return invoke()<HueV2Response<HueV2Matter>>("get_matters")
}

export function getMatter(id: string) {
    return invoke()<HueV2Response<HueV2Matter>>("get_matter", { id })
}

export function getMatterFabrics() {
    return invoke()<HueV2Response<HueV2MatterFabric>>("get_matter_fabrics")
}

export function getMatterFabric(id: string) {
    return invoke()<HueV2Response<HueV2MatterFabric>>("get_matter_fabric", { id })
}

export function getResources() {
    return invoke()<HueV2Response<HueV2Resource>>("get_resources")
}

export function getResource(id: string) {
    return invoke()<HueV2Response<HueV2Resource>>("get_resource", { id })
}

export function getSmartScenes() {
    return invoke()<HueV2Response<HueV2SmartScene>>("get_smart_scenes")
}

export function getSmartScene(id: string) {
    return invoke()<HueV2Response<HueV2SmartScene>>("get_smart_scene", { id })
}

export function setSelectedBridge(mdnsName: string) {
    return invoke()<null>("set_selected_bridge", { mdnsName })
}

export function getDiscoveredBridges() {
    return invoke()<([string, string])[]>("get_discovered_bridges")
}

export function abortDiscover() {
    return invoke()<null>("abort_discover")
}

export type HueV2LightPowerupDimmingMode = "dimming" | "previous"
export type HueV2LightPowerupColor = { mode: HueV2LightColorTemperatureMode; color_temperature: HueV2LightPowerupColorTemperature | null; color: HueV2LightPowerupColorColor | null }
export type HueV2Geolocation = { string: string }
export type HueV2BridgeHome = { id: string; type: HueV2ResourceType; id_v1: string | null; children: HueV2ResourceIdentifier[]; services: HueV2ResourceIdentifier[] }
export type HueV2RelativeRotaryEvent = { action: HueV2RelativeRotaryAction; rotation: HueV2RelativeRotaryRotation }
export type HueV2GroupedLightAlert = { action_values: string[] }
export type HueV2LightPowerupOnMode = "on" | "toggle" | "previous"
export type HueV2LightColorGamutType = "a" | "b" | "c" | "other"
export type HueV2LightSignalingStatus = { signal: HueV2LightSignal; estimated_end: string }
export type HueV2LightColor = { xy: HueV2LightColorXY; gamut: HueV2LightColorGamut | null; gamut_type: HueV2LightColorGamutType }
export type HueV2DeviceBatteryState = "Normal" | "Low" | "Critical"
export type HueV2LightEffects = { effect: HueV2LightEffect; status_values: string[]; status: HueV2LightEffect; effect_values: string[] }
export type HueV2Entertainment = { id: string; type: HueV2ResourceType; id_v1: string | null; owner: HueV2ResourceIdentifier; renderer: boolean; proxy: boolean; equalizer: boolean; max_streams: number | null; segments: HueV2EntertainmentSegments | null }
export type HueV2RelativeRotaryInner = { last_event: HueV2RelativeRotaryEvent | null }
export type HueV2ResourceIdentifier = { rid: string; rtype: HueV2ResourceType }
export type HueV2LightDynamics = { status: HueV2LightDynamicsStatus; status_values: string[]; speed: number; speed_valid: boolean }
export type HueV2LightGradientColor = { xy: HueV2LightColorXY }
export type HueV2LightTimedEffect = "sunrise" | "no_effect"
export type HueV2LightPowerupColorColor = { xy: HueV2LightColorXY }
export type HueV2GroupedLightOn = { on: boolean }
export type HueV2BehaviorInstance = { string: string }
export type HueV2LightDynamicsStatus = "dynamic_palette" | "none"
export type HueV2Zone = { id: string; type: HueV2ResourceType; id_v1: string | null; children: HueV2ResourceIdentifier[]; services: HueV2ResourceIdentifier[]; metadata: HueV2RoomMetadata }
export type HueV2LightGradientPoint = { color: HueV2LightGradientColor }
export type HueV2Device = { id: string; type: HueV2ResourceType; id_v1: string | null; product_data: HueV2DeviceProductData; metadata: HueV2DeviceMetadata; services: HueV2ResourceIdentifier[] }
export type HueV2BehaviorScript = { string: string }
export type HueV2LightLevel = { id: string; type: HueV2ResourceType; id_v1: string | null; owner: HueV2ResourceIdentifier; enabled: boolean; light: HueV2LightLevelInner }
export type HueV2ProductArchetype = "bridge_v2" | "unknown_archetype" | "classic_bulb" | "sultan_bulb" | "flood_bulb" | "spot_bulb" | "candle_bulb" | "luster_bulb" | "pendant_round" | "pendant_long" | "ceiling_round" | "ceiling_square" | "floor_shade" | "floor_lantern" | "table_shade" | "recessed_ceiling" | "recessed_floot" | "single_spot" | "double_spot" | "table_wash" | "wall_lantern" | "wall_shade" | "flexible_lamp" | "ground_spot" | "wall_spot" | "plug" | "hue_go" | "hue_lightstrip" | "hue_iris" | "hue_bloom" | "bollard" | "wall_washer" | "hue_play" | "vintage_bulb" | "vintage_candle_bulb" | "ellipse_bulb" | "triangle_bulb" | "small_globe_bulb" | "large_globe_bulb" | "edison_bulb" | "christmas_tree" | "string_light" | "hue_centris" | "hue_lightstrip_tv" | "hue_lightstrip_pc" | "hue_tube" | "hue_signe" | "pendant_spot" | "ceiling_horizontal" | "ceiling_tube"
export type HueV2GroupedLight = { id: string; type: HueV2ResourceType; id_v1: string | null; owner: HueV2ResourceIdentifier; on: HueV2GroupedLightOn | null; dimming: HueV2GroupedLightDimming | null; alert: HueV2GroupedLightAlert | null }
export type HueV2Temperature = { id: string; type: HueV2ResourceType; id_v1: string | null; owner: HueV2ResourceIdentifier; enabled: boolean; temperature: HueV2TemperatureInner }
export type HueV2DevicePower = { id: string; type: HueV2ResourceType; id_v1: string | null; owner: HueV2ResourceIdentifier; power_state: HueV2DevicePowerState }
export type HueV2LightTimedEffects = { effect: HueV2LightTimedEffect; duration: number | null; status_values: string[]; status: HueV2LightTimedEffect; effect_values: string[] }
export type HueV2LightColorTemperature = { mirek: number; mirek_valid: boolean; mirek_schema: HueV2LightColorTemperatureMirekSchema }
export type HueV2RoomMetadata = { name: string; archetype: HueV2RoomArchetype }
export type HueV2LightEffect = "sparkle" | "fire" | "candle" | "no_effect"
export type HueV2ZigbeeDeviceDiscovery = { string: string }
export type HueV2LightAlert = { action_values: string[] }
export type HueV2SmartScene = { string: string }
export type HueV2RoomArchetype = "LivingRoom" | "Kitchen" | "Dining" | "Bedroom" | "KidsBedroom" | "Bathroom" | "Nursery" | "Recreation" | "Office" | "Gym" | "Hallway" | "Toilet" | "FrontDoor" | "Garage" | "Terrace" | "Garden" | "Driveway" | "Carport" | "Home" | "Downstairs" | "Upstairs" | "TopFloor" | "Attic" | "GuestRoom" | "Staircase" | "Lounge" | "ManCave" | "Computer" | "Studio" | "Music" | "Tv" | "Reading" | "Closet" | "Storage" | "LaundryRoom" | "Balcony" | "Porch" | "Barbecue" | "Pool" | "Other"
export type HueV2LightPowerupDimming = { mode: HueV2LightPowerupDimmingMode; dimming: HueV2LightPowerupDimmingBrightness | null }
export type HueV2LightMetadata = { name: string; archetype: HueV2LightArchetype; fixed_mired: number | null }
export type HueV2LightColorTemperatureMode = "color_temperature" | "color" | "previous"
export type HueV2DeviceMetadata = { name: string; archetype: HueV2ProductArchetype }
export type HueV2LightColorGamutChannel = { x: number; y: number }
export type HueV2Button = { id: string; type: HueV2ResourceType; id_v1: string | null; owner: HueV2ResourceIdentifier; metadata: HueV2ButtonMetadata; button: HueV2ButtonButton }
export type HueV2EntertainmentSegments = { configurable: boolean; max_segments: number; segments: HueV2EntertainmentSegment[] }
export type HueV2LightLevelInner = { light_level: number; light_level_valid: boolean }
export type HueV2Bridge = { string: string }
export type HueV2LightPowerupPreset = "safety" | "powerfail" | "last_on_state" | "custom"
export type HueV2Error = { description: string }
export type HueV2ResourceType = "device" | "bridge_home" | "room" | "zone" | "light" | "button" | "relative_rotary" | "temperature" | "light_level" | "motion" | "entertainment" | "grouped_light" | "device_power" | "zigbee_bridge_connectivity" | "zigbee_connectivity" | "zgp_connectivity" | "bridge" | "zigbee_device_discovery" | "homekit" | "matter" | "matter_fabric" | "scene" | "entertainment_configuration" | "public_image" | "auth_v1" | "behavior_script" | "behavior_instance" | "geofence" | "geofence_client" | "geolocation" | "smart_scene"
export type HueV2Matter = { string: string }
export type HueV2LightPowerup = { preset: HueV2LightPowerupPreset; configured: boolean; on: HueV2LightPowerupOn; dimming: HueV2LightPowerupDimming | null; color: HueV2LightPowerupColor | null }
export type HueV2LightMode = "normal" | "streaming"
export type HueV2LightArchetype = "UnknownArchetype" | "ClassicBulb" | "SultanBulb" | "FloodBulb" | "SpotBulb" | "CandleBulb" | "LusterBulb" | "PendantRound" | "PendantLong" | "CeilingRound" | "CeilingSquare" | "FloorShade" | "FloorLantern" | "TableShade" | "RecessedCeiling" | "RecessedFloot" | "SingleSpot" | "DoubleSpot" | "TableWash" | "WallLantern" | "WallShade" | "FlexibleLamp" | "GroundSpot" | "WallSpot" | "Plug" | "HueGo" | "HueLightstrip" | "HueIris" | "HueBloom" | "Bollard" | "WallWasher" | "HuePlay" | "VintageBulb" | "VintageCandleBulb" | "EllipseBulb" | "TriangleBulb" | "SmallGlobeBulb" | "LargeGlobeBulb" | "EdisonBulb" | "ChristmasTree" | "StringLight" | "HueCentris" | "HueLightstripTv" | "HueLightstripPc" | "HueTube" | "HueSigne" | "PendantSpot" | "CeilingHorizontal" | "CeilingTube"
export type HueV2LightOn = { on: boolean }
export type HueV2ZigbeeConnectivity = { string: string }
export type HueV2LightPowerupOn = { mode: HueV2LightPowerupOnMode; on: HueV2LightOn | null }
export type HueV2LightColorTemperatureMirekSchema = { mirek_minimum: number; mirek_maximum: number }
export type HueV2LightPowerupDimmingBrightness = { brightness: number }
export type HueV2EntertainmentConfiguration = { string: string }
export type HueV2LightGradientMode = "interpolated_palette" | "interpolated_palette_mirrored" | "random_pixelated"
export type HueV2Response<F> = { errors: HueV2Error[]; data: F[] }
export type HueV2LightGradient = { points: HueV2LightGradientPoint[]; mode: HueV2LightGradientMode; points_capable: number; mode_values: string[]; pixel_count: number | null }
export type HueV2ZgpConnectivity = { string: string }
export type HueV2RelativeRotaryAction = "start" | "repeat"
export type HueV2LightColorXY = { x: number; y: number }
export type HueV2LightSignaling = { status: HueV2LightSignalingStatus | null }
export type HueV2DeviceProductData = { model_id: string; manufacturer_name: string; product_name: string; product_archetype: HueV2ProductArchetype; certified: boolean; software_version: string; hardware_platform_type: string | null }
export type HueV2ButtonEvent = "initial_press" | "repeat" | "short_release" | "long_release" | "double_short_release" | "long_press"
export type HueV2TemperatureInner = { temperature: number; temperature_valid: boolean }
export type HueV2Homekit = { string: string }
export type HueV2RelativeRotary = { id: string; type: HueV2ResourceType; id_v1: string | null; owner: HueV2ResourceIdentifier; relative_rotary: HueV2RelativeRotaryInner }
export type HueV2ButtonButton = { last_event: HueV2ButtonEvent }
export type HueV2LightColorGamut = { red: HueV2LightColorGamutChannel; green: HueV2LightColorGamutChannel; blue: HueV2LightColorGamutChannel }
export type HueV2Resource = { id: string; type: HueV2ResourceType; id_v1: string | null }
export type HueV2DevicePowerState = { battery_state: HueV2DeviceBatteryState | null; battery_level: number | null }
export type HueV2GroupedLightDimming = { dimming: number }
export type HueV2Room = { id: string; type: HueV2ResourceType; id_v1: string | null; children: HueV2ResourceIdentifier[]; services: HueV2ResourceIdentifier[]; metadata: HueV2RoomMetadata }
export type HueV2GeofenceClient = { string: string }
export type HueV2RelativeRotaryRotation = { direction: HueV2RelativeRotaryDirection; steps: number; duration: number }
export type HueV2Light = { id: string; type: HueV2ResourceType; id_v1: string | null; owner: HueV2ResourceIdentifier; metadata: HueV2LightMetadata; on: HueV2LightOn; dimming: HueV2LightDimming | null; color_temperature: HueV2LightColorTemperature | null; color: HueV2LightColor | null; dynamics: HueV2LightDynamics | null; alert: HueV2LightAlert | null; signaling: HueV2LightSignaling | null; mode: HueV2LightMode; gradient: HueV2LightGradient | null; effects: HueV2LightEffects | null; timed_effects: HueV2LightTimedEffects | null; powerup: HueV2LightPowerup | null }
export type HueV2Scene = { string: string }
export type HueV2ButtonMetadata = { control_id: number }
export type HueV2EntertainmentSegment = { start: number; length: number }
export type HueV2LightDimming = { brightness: number; min_dim_level: number | null }
export type HueV2LightSignal = "no_signal" | "on_off"
export type HueV2LightPowerupColorTemperature = { mirek: number }
export type HueV2MatterFabric = { string: string }
export type HueV2RelativeRotaryDirection = "clock_wise" | "counter_clock_wise"
